name: CI – Build & Push Strapi Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push
        run: |
          TAG=${GITHUB_SHA::7}
          docker build -t strapi:$TAG .
          docker tag strapi:$TAG ${{ secrets.ECR_REPO }}:$TAG
          docker push ${{ secrets.ECR_REPO }}:$TAG
          echo "IMAGE_URL=${{ secrets.ECR_REPO }}:$TAG" >> $GITHUB_ENV


          
# name: CI – Build & Push Strapi Image

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# env:
#   AWS_REGION: ap-south-1

# jobs:
#   build:
#     name: Build & Push Docker Image
#     runs-on: ubuntu-latest

#     steps:
#       # -----------------------------
#       # Checkout source code
#       # -----------------------------
#       - name: Checkout code
#         uses: actions/checkout@v4

#       # -----------------------------
#       # Configure AWS credentials
#       # -----------------------------
#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ env.AWS_REGION }}

#       # -----------------------------
#       # Login to Amazon ECR
#       # -----------------------------
#       - name: Login to Amazon ECR
#         uses: aws-actions/amazon-ecr-login@v2

#       # -----------------------------
#       # Build & Push Docker Image
#       # -----------------------------
#       - name: Build and push Docker image
#         run: |
#           IMAGE_TAG=${GITHUB_SHA::7}

#           docker build -t strapi:${IMAGE_TAG} .
#           docker tag strapi:${IMAGE_TAG} ${{ secrets.ECR_REPO }}:${IMAGE_TAG}
#           docker push ${{ secrets.ECR_REPO }}:${IMAGE_TAG}

#           echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
